# Generated by Django 4.1 on 2022-10-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_task_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_finished',
        ),
    ]
